//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionSOAP.ServicioPersona {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPersona.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name PersonasGetDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonasGetData", ReplyAction="*")]
        AplicacionSOAP.ServicioPersona.PersonasGetDataResponse PersonasGetData(AplicacionSOAP.ServicioPersona.PersonasGetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonasGetData", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSOAP.ServicioPersona.PersonasGetDataResponse> PersonasGetDataAsync(AplicacionSOAP.ServicioPersona.PersonasGetDataRequest request);
        
        // CODEGEN: Generating message contract since element name nom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPersona", ReplyAction="*")]
        AplicacionSOAP.ServicioPersona.AddPersonaResponse AddPersona(AplicacionSOAP.ServicioPersona.AddPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSOAP.ServicioPersona.AddPersonaResponse> AddPersonaAsync(AplicacionSOAP.ServicioPersona.AddPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonasGetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonasGetData", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionSOAP.ServicioPersona.PersonasGetDataRequestBody Body;
        
        public PersonasGetDataRequest() {
        }
        
        public PersonasGetDataRequest(AplicacionSOAP.ServicioPersona.PersonasGetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PersonasGetDataRequestBody {
        
        public PersonasGetDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonasGetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonasGetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionSOAP.ServicioPersona.PersonasGetDataResponseBody Body;
        
        public PersonasGetDataResponse() {
        }
        
        public PersonasGetDataResponse(AplicacionSOAP.ServicioPersona.PersonasGetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonasGetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSOAP.ServicioPersona.Persona[] PersonasGetDataResult;
        
        public PersonasGetDataResponseBody() {
        }
        
        public PersonasGetDataResponseBody(AplicacionSOAP.ServicioPersona.Persona[] PersonasGetDataResult) {
            this.PersonasGetDataResult = PersonasGetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersona", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionSOAP.ServicioPersona.AddPersonaRequestBody Body;
        
        public AddPersonaRequest() {
        }
        
        public AddPersonaRequest(AplicacionSOAP.ServicioPersona.AddPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        public AddPersonaRequestBody() {
        }
        
        public AddPersonaRequestBody(string nom) {
            this.nom = nom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionSOAP.ServicioPersona.AddPersonaResponseBody Body;
        
        public AddPersonaResponse() {
        }
        
        public AddPersonaResponse(AplicacionSOAP.ServicioPersona.AddPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPersonaResponseBody {
        
        public AddPersonaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : AplicacionSOAP.ServicioPersona.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<AplicacionSOAP.ServicioPersona.WebService1Soap>, AplicacionSOAP.ServicioPersona.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSOAP.ServicioPersona.PersonasGetDataResponse AplicacionSOAP.ServicioPersona.WebService1Soap.PersonasGetData(AplicacionSOAP.ServicioPersona.PersonasGetDataRequest request) {
            return base.Channel.PersonasGetData(request);
        }
        
        public AplicacionSOAP.ServicioPersona.Persona[] PersonasGetData() {
            AplicacionSOAP.ServicioPersona.PersonasGetDataRequest inValue = new AplicacionSOAP.ServicioPersona.PersonasGetDataRequest();
            inValue.Body = new AplicacionSOAP.ServicioPersona.PersonasGetDataRequestBody();
            AplicacionSOAP.ServicioPersona.PersonasGetDataResponse retVal = ((AplicacionSOAP.ServicioPersona.WebService1Soap)(this)).PersonasGetData(inValue);
            return retVal.Body.PersonasGetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSOAP.ServicioPersona.PersonasGetDataResponse> AplicacionSOAP.ServicioPersona.WebService1Soap.PersonasGetDataAsync(AplicacionSOAP.ServicioPersona.PersonasGetDataRequest request) {
            return base.Channel.PersonasGetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSOAP.ServicioPersona.PersonasGetDataResponse> PersonasGetDataAsync() {
            AplicacionSOAP.ServicioPersona.PersonasGetDataRequest inValue = new AplicacionSOAP.ServicioPersona.PersonasGetDataRequest();
            inValue.Body = new AplicacionSOAP.ServicioPersona.PersonasGetDataRequestBody();
            return ((AplicacionSOAP.ServicioPersona.WebService1Soap)(this)).PersonasGetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSOAP.ServicioPersona.AddPersonaResponse AplicacionSOAP.ServicioPersona.WebService1Soap.AddPersona(AplicacionSOAP.ServicioPersona.AddPersonaRequest request) {
            return base.Channel.AddPersona(request);
        }
        
        public void AddPersona(string nom) {
            AplicacionSOAP.ServicioPersona.AddPersonaRequest inValue = new AplicacionSOAP.ServicioPersona.AddPersonaRequest();
            inValue.Body = new AplicacionSOAP.ServicioPersona.AddPersonaRequestBody();
            inValue.Body.nom = nom;
            AplicacionSOAP.ServicioPersona.AddPersonaResponse retVal = ((AplicacionSOAP.ServicioPersona.WebService1Soap)(this)).AddPersona(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSOAP.ServicioPersona.AddPersonaResponse> AplicacionSOAP.ServicioPersona.WebService1Soap.AddPersonaAsync(AplicacionSOAP.ServicioPersona.AddPersonaRequest request) {
            return base.Channel.AddPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSOAP.ServicioPersona.AddPersonaResponse> AddPersonaAsync(string nom) {
            AplicacionSOAP.ServicioPersona.AddPersonaRequest inValue = new AplicacionSOAP.ServicioPersona.AddPersonaRequest();
            inValue.Body = new AplicacionSOAP.ServicioPersona.AddPersonaRequestBody();
            inValue.Body.nom = nom;
            return ((AplicacionSOAP.ServicioPersona.WebService1Soap)(this)).AddPersonaAsync(inValue);
        }
    }
}
